### ISSUE TITLE
index.js is missing

### ISSUE THREAD

**Issue by jimphelps** [emanuele-f/lumen-control#1]
Hi,
I'm trying to use your version of lumen nodejs server;
it seems that you have a modified version of sandeepmistry's index.js, which is missing in this repo.
Could you please provide this?
thank you

the error:
missing file:
var Lumen = require("/home/emanuele/src/node-lumen/index.js");
error on my version of index.js
    lumen.rgbColor(rgb_to_99(rgb), function() {
          ^
TypeError: Object {"uuid":"7c669dxxxx"} has no method 'rgbColor'

**Comment by emanuele-f** [comment]
Hi,
yes, there is a pending pull request [here](https://github.com/sandeepmistry/node-lumen/pull/2). You can clone my own fork at https://github.com/emanuele-f/node-lumen. I'll add this info to the readme file.
Thank you.
Please, feel free to leave comments and contribute.

**Comment by emanuele-f** [comment]
The modified code is now available into the official npm lumen module. lumen-control now uses new api: @e621fc4407
