### ISSUE TITLE
Client timeout

### ISSUE THREAD

**Issue by stefanproell** [emanuele-f/lumen-control#2]
Hello,
I am trying to run the lumen-control tool, but I can't establish a connection.

```
~$ sudo node index.js 
Listening on port 7878
Client Connected
Start discovering... 
Lumen bound: {"uuid":"20cd39a75dec","id":"20cd39a75dec","address":"20:cd:39:a7:5d:ec"}
Connecting...
Client timeout
Client disconnected
Client Connected
Connection attempt hang
Connecting...
Client timeout
Client disconnected
```

The light bulp seems to be detected, but the conenczion cant' be opened. Do you have any suggestions? The device is not paired, I am using a bluetooth USB dongle with Ubuntu Linux 14.10

**Comment by emanuele-f** [comment]
Hi, it's really late to reply but I'll try anyway. I've dropped this project for a while, sorry for delay.

There is an [open bug](https://github.com/sandeepmistry/noble/issues/229) on the noble library which prevents device reconnection. When you experience the "Connection attempt hang", we should abort the connection attempt and retry, but this can only be done with a patched version of noble. I've included the `noble_disconnect.patch` in the server directory.

I've just reworked the lumen controller to make it more stable. If you are interested in Home Assistant integration, you can give it a try.
